general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300          # 5 minutes
    on_timeout = hyprlock  # Lock screen
}

listener {
    timeout = 1800          # 30 minutes
    on_timeout = hyprctl dispatch dpms off  # Turn off displays
    on_resume = hyprctl dispatch dpms on    # Turn displays back on
}
