---@diagnostic disable: undefined-global
-- onedark_pro_dark.lua
local lush = require("lush")
local hsl = lush.hsl

-- Color palette for onedark_dark variant
local colors = {
  bg = hsl(0, 0, 0),
  fg = hsl(220, 20, 60),
  red = hsl(355, 65, 65),
  green = hsl(120, 20, 65),
  yellow = hsl(50, 75, 75),
  orange = hsl(15, 70, 65),
  purple = hsl(245, 75, 60),
  light_purple = hsl(245, 75, 60).lighten(10),
  lighter_purple = hsl(245, 75, 60).lighten(20).rotate(-10).desaturate(10),
  cyan = hsl(187, 47, 55),
  blue = hsl(213, 75, 50),
  light_blue = hsl(213, 75, 50).lighten(10),
  lighter_blue = hsl(213, 75, 50).lighten(20),
  white = hsl(219, 14, 71),
  black = hsl(222, 15, 13),
  gray = hsl(219, 10, 40),
  highlight = hsl(221, 15, 20),
  comment = hsl(220, 6, 53),
  gutter_fg = hsl(222, 14, 34),
  gutter_bg = hsl(0, 0, 0),
  line_bg = hsl(221, 15, 20),
  light_red = hsl(355, 65, 65).lighten(10),
  dark_yellow = hsl(50, 75, 75).darken(10),
  light_gray = hsl("#abb2bf").lighten(20),
}

-- Define the theme
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    -- Base highlights
    Normal({ fg = colors.fg, bg = colors.bg }),
    NormalFloat({ fg = colors.fg, bg = colors.black }),
    Visual({ bg = colors.highlight }),
    VisualNOS({ bg = colors.highlight }),
    Search({ fg = colors.black, bg = colors.yellow }),
    IncSearch({ fg = colors.black, bg = colors.yellow }),
    Cursor({ bg = colors.bg, fg = colors.purple }),
    CursorLine({ bg = colors.line_bg }),
    CursorColumn({ bg = colors.line_bg }),
    ColorColumn({ bg = colors.line_bg }),
    LineNr({ fg = colors.gutter_fg, bg = colors.gutter_bg }),
    CursorLineNr({ fg = colors.yellow, bg = colors.line_bg }),
    VertSplit({ fg = colors.highlight, bg = colors.bg }),
    Folded({ fg = colors.gray, bg = colors.black }),
    FoldColumn({ fg = colors.gray, bg = colors.gutter_bg }),
    SignColumn({ fg = colors.fg, bg = colors.gutter_bg }),
    StatusLine({ fg = colors.fg, bg = colors.black }),
    StatusLineNC({ fg = colors.gray, bg = colors.black }),
    Pmenu({ fg = colors.fg, bg = colors.black }),
    PmenuSel({ fg = colors.black, bg = colors.blue }),
    PmenuSbar({ bg = colors.highlight }),
    PmenuThumb({ bg = colors.gray }),
    MatchParen({ fg = colors.yellow, bg = colors.highlight }),
    NonText({ fg = colors.gray }),
    SpecialKey({ fg = colors.gray }),

    -- Syntax highlighting
    Comment({ fg = colors.comment, gui = "italic" }),
    Constant({ fg = colors.light_blue }),
    String({ fg = colors.green }),
    Character({ fg = colors.green }),
    Number({ fg = colors.yellow }),
    Boolean({ fg = colors.yellow }),
    Float({ fg = colors.yellow }),
    Identifier({ fg = colors.lighter_purple }),
    Function({ fg = colors.blue }),
    Statement({ fg = colors.purple }),
    Conditional({ fg = colors.purple }),
    Repeat({ fg = colors.purple }),
    Label({ fg = colors.purple }),
    Operator({ fg = colors.fg }),
    Keyword({ fg = colors.lighter_purple }),
    Exception({ fg = colors.purple }),
    PreProc({ fg = colors.yellow }),
    Include({ fg = colors.purple }),
    Define({ fg = colors.purple }),
    Macro({ fg = colors.purple }),
    PreCondit({ fg = colors.yellow }),
    Type({ fg = colors.yellow.de(20) }),
    StorageClass({ fg = colors.yellow }),
    Structure({ fg = colors.yellow }),
    Typedef({ fg = colors.yellow }),
    Special({ fg = colors.lighter_purple }),
    SpecialChar({ fg = colors.orange }),
    Tag({ fg = colors.purple }),
    Delimiter({ fg = colors.yellow.de(20) }),
    SpecialComment({ fg = colors.gray }),
    Debug({ fg = colors.fg }),
    Underlined({ fg = colors.blue, gui = "underline" }),
    Ignore({ fg = colors.gray }),
    Error({ fg = colors.red, gui = "bold" }),
    Todo({ fg = colors.purple, gui = "bold" }),

    -- Git highlighting
    GitSignsAdd({ fg = colors.green }),
    GitSignsChange({ fg = colors.yellow }),
    GitSignsDelete({ fg = colors.red }),

    -- General Treesitter groups
    -- These groups are used by all languages
    TSAttribute({ fg = colors.yellow }),
    TSBoolean({ fg = colors.yellow }),
    TSCharacter({ fg = colors.green }),
    TSComment({ fg = colors.comment, gui = "italic" }),
    TSConditional({ fg = colors.purple }),
    TSConstant({ fg = colors.orange }),
    TSConstBuiltin({ fg = colors.yellow }),
    TSConstMacro({ fg = colors.orange }),
    TSConstructor({ fg = colors.yellow, gui = "bold" }),
    TSError({ fg = colors.red }),
    TSException({ fg = colors.purple }),
    TSField({ fg = colors.red }),
    TSFloat({ fg = colors.yellow }),
    TSFunction({ fg = colors.blue }),
    TSFuncBuiltin({ fg = colors.orange }),
    TSFuncMacro({ fg = colors.blue }),
    TSInclude({ fg = colors.purple }),
    TSKeyword({ fg = colors.purple }),
    TSKeywordFunction({ fg = colors.purple }),
    TSKeywordOperator({ fg = colors.purple }),
    TSLabel({ fg = colors.red }),
    TSMethod({ fg = colors.blue }),
    TSNamespace({ fg = colors.yellow }),
    TSNone({}),
    TSNumber({ fg = colors.yellow }),
    TSOperator({ fg = colors.fg }),
    TSParameter({ fg = colors.red }),
    TSParameterReference({ fg = colors.red }),
    TSProperty({ fg = colors.red }),
    TSPunctDelimiter({ fg = colors.fg }),
    TSPunctBracket({ fg = colors.fg }),
    TSPunctSpecial({ fg = colors.orange }),
    TSRepeat({ fg = colors.purple }),
    TSString({ fg = colors.green }),
    TSStringRegex({ fg = colors.orange }),
    TSStringEscape({ fg = colors.orange }),
    TSSymbol({ fg = colors.orange }),
    TSTag({ fg = colors.red }),
    TSTagDelimiter({ fg = colors.light_gray }),
    TSText({ fg = colors.fg }),
    TSStrong({ fg = colors.fg, gui = "bold" }),
    TSEmphasis({ fg = colors.fg, gui = "italic" }),
    TSUnderline({ fg = colors.fg, gui = "underline" }),
    TSStrike({ fg = colors.fg, gui = "strikethrough" }),
    TSTitle({ fg = colors.yellow, gui = "bold" }),
    TSLiteral({ fg = colors.green }),
    TSURI({ fg = colors.blue, gui = "underline" }),
    TSMath({ fg = colors.fg }),
    TSTextReference({ fg = colors.blue }),
    TSEnvironment({ fg = colors.fg }),
    TSEnvironmentName({ fg = colors.fg }),
    TSNote({ fg = colors.purple, gui = "bold" }),
    TSWarning({ fg = colors.yellow, gui = "bold" }),
    TSDanger({ fg = colors.red, gui = "bold" }),
    TSType({ fg = colors.yellow }),
    TSTypeBuiltin({ fg = colors.yellow }),
    TSVariable({ fg = colors.purple }),
    TSVariableBuiltin({ fg = colors.yellow }),

    -- Language-specific Treesitter groups
    bashTSFuncBuiltin({ TSFuncBuiltin }),
    bashTSParameter({ TSParameter }),
    -- cTSType({ TSType }),
    -- cTSStorage({ TSStorageClass }),
    cssTSProperty({ TSProperty }),
    cssTSString({ TSString }),
    -- goTSType({ TSType }),
    -- goTSVariable({ TSVariable }),
    htmlTSTag({ TSTag }),
    htmlTSTagAttribute({ TSAttribute }),
    -- javaTSType({ TSType }),
    -- javaTSVariable({ TSVariable }),
    jsonTSLabel({ TSLabel }),
    luaTSConstructor({ TSConstructor }),
    luaTSField({ TSField }),
    -- markdownTSURI({ TSURI }),
    -- markdownTSTextReference({ TSTextReference }),
    -- markdownTSLiteral({ TSLiteral }),
    -- markdownTSStrong({ TSStrong }),
    -- markdownTSEmphasis({ TSEmphasis }),
    -- pythonTSType({ TSType }),
    -- pythonTSParameter({ TSParameter }),
    -- rubyTSSymbol({ TSSymbol }),
    -- rustTSType({ TSType }),
    -- rustTSVariable({ TSVariable }),
    tomlTSProperty({ TSProperty }),
    tomlTSString({ TSString }),
    vimTSVariable({ TSVariable }),
    vimTSBoolean({ TSBoolean }),
    yamlTSField({ TSField }),

    -- Additional TypeScript/TSX refinements
    typescriptTSConstructor({ TSConstructor }),
    typescriptTSKeywordOperator({ TSKeywordOperator }),
    typescriptTSTypeBuiltin({ TSTypeBuiltin }),
    tsxTSConstructor({ TSConstructor }),
    tsxTSKeywordOperator({ TSKeywordOperator }),
    tsxTSTypeBuiltin({ TSTypeBuiltin }),

    -- Semantic tokens (for newer Treesitter versions)
    sym("@variable.tsx")({ TSVariable }),
    sym("@variable")({ TSVariable }),
    sym("@tag.delimiter.tsx")({ TSTagDelimiter }),
    sym("@tag.attribute.tsx")({ fg = colors.lighter_blue }),
    sym("@keyword.import.tsx")({ fg = colors.lighter_purple }),
    sym("@keyword.function.tsx")({ fg = colors.lighter_purple }),
    sym("@type.tsx")({ fg = colors.purple }),
    -- ["@lsp.type.class"] { fg = colors.yellow },
    -- ["@lsp.type.decorator"] { TSAttribute },
    -- ["@lsp.type.enum"]           { TSType },
    -- ["@lsp.type.enumMember"]     { TSProperty },
    -- ["@lsp.type.function"]       { TSFunction },
    -- ["@lsp.type.interface"]      { TSType },
    -- ["@lsp.type.macro"]          { TSConstMacro },
    -- ["@lsp.type.method"]         { TSMethod },
    -- ["@lsp.type.namespace"]      { TSNamespace },
    -- ["@lsp.type.parameter"]      { TSParameter },
    -- ["@lsp.type.property"]       { TSProperty },
    -- ["@lsp.type.struct"]         { TSType },
    -- ["@lsp.type.type"]           { TSType },
    -- ["@lsp.type.typeParameter"]  { TSTypeBuiltin },
    -- ["@lsp.type.variable"]       { TSVariable },

    -- SQL specific highlights
    sqlKeyword({ fg = colors.purple, gui = "bold" }),
    sqlSpecial({ fg = colors.yellow }),
    sqlType({ fg = colors.blue }),
    sqlStatement({ fg = colors.purple }),
    sqlFunction({ fg = colors.yellow }),
    sqlOperator({ fg = colors.orange }),
    sqlString({ fg = colors.green }),
    sqlNumber({ fg = colors.orange }),
    sqlComment({ fg = colors.comment, gui = "italic" }),
    sqlTable({ fg = colors.red, gui = "bold" }),
    sqlColumn({ fg = colors.fg }),

    -- C# specific highlights
    csharpNamespace({ fg = colors.purple }),
    csharpClass({ fg = colors.yellow, gui = "bold" }),
    csharpEnum({ fg = colors.yellow }),
    csharpStructure({ fg = colors.yellow }),
    csharpTypeParameter({ fg = colors.light_blue }),
    csharpInterface({ fg = colors.light_blue, gui = "italic" }),
    csharpMethod({ fg = colors.blue }),
    csharpProperty({ fg = colors.light_red }),
    csharpEvent({ fg = colors.yellow }),
    csharpAttribute({ fg = colors.dark_yellow }),
    csharpStatement({ fg = colors.purple }),
    csharpConditional({ fg = colors.purple }),
    csharpRepeat({ fg = colors.purple }),
    csharpException({ fg = colors.purple, gui = "bold" }),
    csharpStorageClass({ fg = colors.purple }),
    csharpAsync({ fg = colors.purple, gui = "italic" }),
    csharpConstant({ fg = colors.orange }),
    csharpTypeDeclaration({ fg = colors.yellow }),
    csharpGenericBraces({ fg = colors.fg }),
    csharpDocumentation({ fg = colors.comment, gui = "italic" }),
    csharpDocumentationTag({ fg = colors.comment, gui = "bold,italic" }),

    -- Treesitter SQL highlights
    TSKeywordSQL({ sqlKeyword }),
    TSOperatorSQL({ sqlOperator }),
    TSFunctionSQL({ sqlFunction }),
    TSFieldSQL({ sqlColumn }),
    TSTypeSQL({ sqlType }),

    -- Treesitter C# highlights
    TSNamespaceCSharp({ csharpNamespace }),
    TSTypeCSharp({ csharpClass }),
    TSTypeParameterCSharp({ csharpTypeParameter }),
    TSMethodCSharp({ csharpMethod }),
    TSPropertyCSharp({ csharpProperty }),
    TSConstantCSharp({ csharpConstant }),
    TSAttributeCSharp({ csharpAttribute }),
    TSKeywordCSharp({ csharpStatement }),
    TSConditionalCSharp({ csharpConditional }),
    TSRepeatCSharp({ csharpRepeat }),
    TSExceptionCSharp({ csharpException }),

    -- Neo-tree highlight groups
    NeoTreeNormal({ fg = hsl(200, 40, 50), bg = hsl(200, 10, 10) }),
    NeoTreeNormalNC({ NeoTreeNormal }),
    NeoTreeVertSplit({ fg = hsl(200, 20, 40) }),
    NeoTreeWinSeparator({ NeoTreeVertSplit }),
    NeoTreeEndOfBuffer({ fg = hsl(200, 10, 10) }),
    NeoTreeRootName({ fg = hsl(300, 60, 60), bold = true }),
    NeoTreeFileName({ fg = hsl(180, 40, 70) }),
    NeoTreeFileIcon({ fg = hsl(220, 40, 70) }),
    NeoTreeSymbolicLinkTarget({ fg = hsl(300, 40, 70) }),
    NeoTreeIndentMarker({ fg = hsl(200, 20, 40) }),
    NeoTreeGitAdded({ fg = hsl(120, 60, 50) }),
    NeoTreeGitConflict({ fg = hsl(0, 60, 50) }),
    NeoTreeGitDeleted({ fg = hsl(0, 60, 50) }),
    NeoTreeGitIgnored({ fg = hsl(0, 0, 50) }),
    NeoTreeGitModified({ fg = hsl(40, 60, 50) }),
    NeoTreeGitUnstaged({ fg = hsl(0, 60, 50) }),
    NeoTreeGitUntracked({ fg = hsl(180, 60, 50) }),
    NeoTreeGitStaged({ fg = hsl(120, 60, 50) }),

    NoiceCmdline({ fg = hsl(200, 40, 50), bg = hsl(200, 10, 10) }),
    NoiceCmdlineIcon({ fg = hsl(300, 60, 60) }),
    NoiceCmdlineIconSearch({ fg = hsl(60, 60, 60) }),
    NoiceCmdlinePopup({ fg = hsl(180, 40, 70), bg = hsl(200, 15, 15) }),
    NoiceCmdlinePopupBorder({ fg = hsl(200, 30, 60) }),
    NoiceCmdlinePrompt({ fg = hsl(120, 40, 60), bold = true }),
  }
end)

return theme
